### ISSUE TITLE
Docker is sunsetting free teams

### ISSUE THREAD

**Issue by alexanderpann** [coolya/mbeddr.build.docker#16]
> Docker is sunsetting Free Team organizations
> 
> Free Team organizations are a legacy subscription tier that no longer exists. This tier included many of the same features, rates, and functionality as a paid Docker Team subscription.
> 
> After reviewing the list of accounts that are members of legacy Free Team organizations, we’ve identified yours as potentially being one of them.
> 
> If you own a legacy Free Team organization, access to paid features — including private repositories — will be suspended on April 14, 2023 (11:59 pm UTC). Upgrade your subscription before April 14, 2023 to continue accessing your organization.
> 
> If you don’t upgrade to a paid subscription, Docker will retain your organization data for 30 days, after which it will be subject to deletion. During that time, you will maintain access to any images in your public repositories, though rate limitations will apply. At any point during the 30-day period, you can restore access to your organization account if you upgrade to a paid subscription. Visit our [FAQ](https://em.docker.com/NzkwLVNTQi0zNzUAAAGKf9wIBRrkrFE1GslYy3oeT4XHYbqV5Fl_FQ2-k8jjnEgc20yAaaWdk059Svx6bfrGrO3YeLBSXKTXSSE=) for more information.

I believe this affects the publishing of our Docker images to Docker Hub. We could create a new single-user account or just (continue) publish(ing) to GitHub and fetch the images from there. The third option would be to apply for the Docker-Sponsored Open Source Program, but I am not sure if we would be even eligible.

**Comment by Vad1mo** [comment]
If, for some reason, the Docker-Sponsored Open-Source Program isn't working out, we are happy to help you out. We operate a Harbor-based [container registry as a service ](https://container-registry.com/)that has many benefits over most of the other registries out there.

There are also features regarding containerized image distribution, that might be valuable too as well.

**Comment by sergej-koscejev** [comment]
I'm in favor of just publishing to GitHub.

**Comment by alexanderpann** [comment]
> On March 14, 2023, we emailed you about your Free Team subscription, outlining our intention to sunset that plan. After listening to the concerns of the community, we’ve decided to reverse course, and are no longer sunsetting the Free Team plan.
